// Icon ids the app may reference. Each id maps to an external, SVGO-optimized
// Fluent Emoji file at public/icons/<id>.svg (see iconManifest.ts, generated by
// scripts/fetch-icons.mjs). Icons are never inlined in bulk.
//
// APPEND-ONLY: share-link hashes encode icons by their index in these lists,
// so never reorder or remove an entry once released.

export const CHORE_ICON_IDS = [
  'alarm', 'apple', 'abc', 'backpack', 'ball', 'bath', 'bathroom', 'battery', 'bed', 'bedroom', 'bike', 'bone',
  'books', 'broom', 'calendar', 'car', 'cereal', 'closet', 'coat', 'comb', 'cupboard', 'desk', 'dishwasher',
  'dog-leash', 'drawer', 'duster', 'dustpan', 'face-wash', 'fish', 'folded-clothes', 'fridge', 'grocery-bag',
  'hamper', 'hanger', 'iron', 'laundry-basket', 'lawn-mower', 'litter', 'lunchbox', 'mail', 'microwave', 'mirror',
  'moon', 'mop', 'music', 'note', 'pajamas', 'pencil', 'pet-bowl', 'pet-brush', 'pet-cage', 'place-setting',
  'plate', 'poop-bag', 'pot', 'potty', 'rake', 'recycle', 'seedling', 'shirt', 'shoes', 'sink', 'snow-shovel',
  'soap', 'socks', 'sofa', 'sponge', 'spray-bottle', 'star', 'sun', 'tablet', 'teddy', 'toilet', 'toilet-paper',
  'toothbrush', 'towel', 'toy-box', 'trash-can', 'tree', 'utensils', 'vacuum', 'washing-machine', 'water',
  'water-bottle', 'watering-can', 'weed', 'whisk', 'window',
] as const;

export const AVATAR_ICON_IDS = [
  'avatar-bear', 'avatar-cat', 'avatar-dog', 'avatar-fox', 'avatar-lion', 'avatar-owl', 'avatar-penguin',
  'avatar-rabbit', 'avatar-rocket', 'avatar-panda', 'avatar-tiger', 'avatar-koala', 'avatar-frog', 'avatar-unicorn',
  'avatar-dinosaur', 'avatar-robot',
] as const;

/** Stickers and badges for reward charts. */
export const REWARD_ICON_IDS = [
  'reward-star', 'reward-trophy', 'reward-medal', 'reward-rosette', 'reward-crown', 'reward-heart',
  'reward-rainbow', 'reward-gift', 'reward-party', 'reward-sparkles',
] as const;

export type ChoreIconId = (typeof CHORE_ICON_IDS)[number];
export type AvatarIconId = (typeof AVATAR_ICON_IDS)[number];
export type RewardIconId = (typeof REWARD_ICON_IDS)[number];
export type IconId = ChoreIconId | AvatarIconId | RewardIconId;

export const ALL_ICON_IDS: readonly IconId[] = [...CHORE_ICON_IDS, ...AVATAR_ICON_IDS, ...REWARD_ICON_IDS];
export const ICON_IDS: ReadonlySet<string> = new Set<string>(ALL_ICON_IDS);

export function isIconId(value: unknown): value is IconId {
  return typeof value === 'string' && ICON_IDS.has(value);
}
